services:
  - type: web
    name: chess-server
    env: node
    rootDir: chess-web
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    branch: main
    autoDeploy: true 